project_name: feverscreen
dist: dist

release:
  github:
    owner: feverscreen
    name: feverscreen
  file_name_template: '{{.Tag}}'

before:
  hooks:
    - tsc -p ./webserver
    - rollup ./webserver/static/js/feverscreen.js --file ./webserver/static/js/bundle.js --format iife

builds:
- id: feverscreen
  binary: feverscreen
  main: ./cmd/feverscreen
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  hooks:
    pre: packr
    post: packr clean
  ldflags: -s -w -X main.version={{.Version}}
- id: leptond
  binary: leptond
  main: ./cmd/leptond
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}

nfpms:
-
  vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Core Developers <coredev@cacophony.org.nz>
  description: Fever detection using thermal cameras
  license: GPL v3.0
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "_release/feverscreen.service": "/etc/systemd/system/feverscreen.service"
    "_release/leptond.service": "/etc/systemd/system/leptond.service"
    "webserver/_release/managementd-avahi.service": "/etc/avahi/services/managementd.service"
  scripts:
    postinstall: "_release/postinstall.sh"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
