project_name: thermal-recorder
dist: dist

release:
  github:
    owner: TheCacophonyProject
    name: thermal-recorder
  name_template: '{{.Tag}}'

builds:
- binary: thermal-recorder
  main: ./cmd/thermal-recorder
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
- binary: leptond
  main: ./cmd/leptond
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}

nfpm:
  vendor: The Cacophony Project
  homepage: http://cacophony.org.nz/
  maintainer: Menno Finlay-Smits <menno@cacophony.org.nz>
  description: Record thermal video footage from FLIR Lepton 3 camera
  license: GPL v3.0
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
  formats:
    - deb
  bindir: /usr/bin
  files:
    "thermal-recorder.service": "/etc/systemd/system/thermal-recorder.service"
    "leptond.service": "/etc/systemd/system/leptond.service"
    "set-thermal-recorder-output/set-thermal-recorder-output.service": "/etc/systemd/system/set-thermal-recorder-output.service"
    "set-thermal-recorder-output/set-thermal-recorder-output": "/usr/bin/set-thermal-recorder-output"

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
