project_name: thermal-recorder
release:
  github:
    owner: TheCacophonyProject
    name: thermal-recorder
  name_template: '{{.Tag}}'
builds:
- binary: thermal-recorder
  main: ./cmd/thermal-recorder
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - "7"
  ldflags: -s -w -X main.version={{.Version}}
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}'
  format: tar.gz
  files:
  - thermal-recorder.service
  - thermal-recorder-TEMPLATE.yaml
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
dist: dist
