language: go
go:
- 1.13.x
script:
- go vet ./...
- go test ./...
deploy:
  provider: releases
  api_key:
    secure: VMUWw4nPxzK9mqz1e53VGkzp+ZPQzcpicXXIgNYF6YNkMqBXzniflSom8YO4xySoPUiMtvV56lQ96dOSTWf+IXwo4uyPviFGVmHTvB18a2gS83BfRTBRKioBQH0pDtna9YVsg24jQrTYIPu9zo/yFpSJmZrU2Aky64evlnHRBhchnwyg0594nerqpAIlFVh0YtqSX9U9WINzp9b2Y+k2AdFFcs8IBEEasUZJBhx/RsyB5TTeWX/OSWNcqPV1sHSbLWJNlLb1/PHIOPeH+8Rf+bOxKexUGj8VELRSWc0n0hqcFIS6/722tP++jxOkFTj1RnMNGhezr7V7+tDFQF/wgenZXd9z5fPUCCUcZAEK3AUIwsjCO7pxlsN0+opSVtXyV2w15kXkCtNYGo5XJPdEXSWdDG6IZHtgBvC9mgfp2L6l6ugPdR7MlmRMysMOJaTbk2/kCQfT2Dm8Qh15uNGEOP51+SNM+9Hes56NilyJg2XL1Y234ubJBMkQ7dypgUPI/tpfn6xWUOXSXt7Q8K74GH+sCbo1jUU3fA3BpIvBwrzvn6PLXaUETofyEJT62YXVfX4FS70n+dmSp2lLcw1hAErNiVTtgwtdh81RpuH21cWZ7QaA0wZUcz8WjxoW98KL1VBZUmBUf9TfSoSOXTrlZTsQKGnW6kNoBzn8xdapdwE=
  file: dist/*.deb
