language: go
go:
- 1.13.x
script:
- go vet ./...
- go test ./...
deploy:
  provider: releases
  api_key:
    secure: R3mbQYW4KXg+SQ73VZVD4qjCn1+O0+ZI+aFP55iNSKz1jn1h3imsdP/nf/dZB1FpNXiiX4jZ0Z+KNobuketVQp5DMExeB4VhKPHIwSVwiU5VkdLh30BBA6T2Scv4arqY+QaKkcMIdhaP9dfvZYHqmnN+d5bdK5Z2qhSNXue4gUbeH8Wj2zSw3ttHXXmnYE1J0/maZfFBrNpVsShxsC0QpSbm3FKEO3u6EU19mS4CzU9rtOYs/1wkXp7iFYEIvwysis7N/1kkd9ZAhAHHdK5kdRK0YxIp7uOFCYokVeDdI1/kgfEOVlL6e9fVIAMbBQ8l+26TJrwUIlU2NzXKwPjHQegB1zJB8DWTBIXoh+5YOUWPJiV/TZ9Jxtx1bCYGpMROJpopQffu4MPtE8SzdUA1766vMgj1NeJcBolvFrEO68+BJGLp9wLpIOXmOzc/q3s/bvtHCk++txqPde66Oxbfi6L6DETR1Dq7U00aOza0hB9PEYtY12cNIiEs454y/vKE+A4Lw1a9ln8N32yX9FCEEDwASBkCx6xxVWwXQoVPs+LDueg5LQ9/dBlUOxd7BzeWpA4cKJu56OYPZOqsxSQWMOetG9A0OMgHsC2Evb48s7k/L2ONKwYpBkMeoC7m89t8VgZRvzRc6XJdpdBwPkyQyIRYKoqSwMYa5N+gFG+Bb9c=
  file: dist\*.deb
  on:
    tags: true
    go: "1.13.x"
