dist: bionic
language: go
go:
- 1.13.x
node_js:
  - lts/*
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install stable
before_script:
  - sudo apt-get -y install npm
  - sudo npm install -g typescript
  - sudo npm install -g rollup
script:
- go mod tidy
- git diff --exit-code --quiet || (echo "Please run 'go mod tidy' to clean up the 'go.mod' and 'go.sum' files."; false)
- go vet ./...
- go test ./...

deploy:
  provider: script
  skip_cleanup: true
  script: make release
  on:
    tags: true
    go: "1.13.x"
