dist: bionic
language: go
go:
- 1.13.x
node_js:
  - 12
script:
- go mod tidy
- git diff --exit-code --quiet || (echo "Please run 'go mod tidy' to clean up the 'go.mod' and 'go.sum' files."; false)
- go vet ./...
- go test ./...

before_install:
  - sudo node -v
  - sudo nvm use node
  - sudo node -v
  - sudo nvm install -g typescript
  - sudo nvm install -g rollup

deploy:
  provider: script
  skip_cleanup: true
  script: make release
  on:
    tags: true
    go: "1.13.x"
