# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  branch = "master"
  name = "github.com/TheCacophonyProject/lepton3"

[[constraint]]
  name = "periph.io/x/periph"
  source = "https://github.com/TheCacophonyProject/periph.git"

[[constraint]]
  name = "github.com/TheCacophonyProject/go-cptv"
  branch = "master"


[[constraint]]
  name = "github.com/kelvins/sunrisesunset"
  branch = "master"